import mongoose from 'mongoose';

/**
 * Payment Schema
 * Tracks all payments against invoices
 * Supports full, partial, and installment payments
 */

const paymentSchema = new mongoose.Schema({
  // Payment identification
  paymentNumber: {
    type: String,
    required: false,  // Generated by pre-save hook
    unique: true,
    sparse: true  // Allow null/undefined before generation
  },
  paymentDate: {
    type: Date,
    required: true,
    default: Date.now
  },
  
  // Related invoice and customer
  invoiceId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Invoice',
    required: true
  },
  invoiceNumber: {
    type: String,
    required: true
  },
  customerId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Customer',
    required: true
  },
  customerName: {
    type: String,
    required: true
  },
  
  // Payment details
  amount: {
    type: Number,
    required: true,
    min: 0
  },
  paymentMethod: {
    type: String,
    enum: ['CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'CHEQUE', 'OTHER'],
    required: true,
    default: 'CASH'
  },
  
  // Additional payment info
  transactionId: {
    type: String,
    default: ''
  },
  chequeNumber: {
    type: String,
    default: ''
  },
  bankDetails: {
    type: String,
    default: ''
  },
  
  // Next payment tracking
  remainingAmount: {
    type: Number,
    default: 0
  },
  nextDueDate: {
    type: Date,
    default: null
  },
  nextDueAmount: {
    type: Number,
    default: 0
  },
  
  // Payment status
  status: {
    type: String,
    enum: ['SUCCESS', 'PENDING', 'FAILED', 'CANCELLED'],
    default: 'SUCCESS'
  },
  
  // Notes
  notes: {
    type: String,
    default: ''
  },
  
  // Audit trail
  recordedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
}, {
  timestamps: true
});

// Indexes
paymentSchema.index({ paymentNumber: 1 });
paymentSchema.index({ invoiceId: 1 });
paymentSchema.index({ customerId: 1 });
paymentSchema.index({ paymentDate: -1 });
paymentSchema.index({ nextDueDate: 1 });
paymentSchema.index({ status: 1 });

// Auto-generate payment number
paymentSchema.pre('save', async function(next) {
  if (this.isNew && !this.paymentNumber) {
    const year = new Date().getFullYear();
    const month = String(new Date().getMonth() + 1).padStart(2, '0');
    
    const lastPayment = await mongoose.model('Payment')
      .findOne()
      .sort({ createdAt: -1 });
    
    let sequence = 1;
    if (lastPayment && lastPayment.paymentNumber) {
      const lastSeq = parseInt(lastPayment.paymentNumber.split('-').pop());
      sequence = lastSeq + 1;
    }
    
    this.paymentNumber = `PAY-${year}${month}-${String(sequence).padStart(4, '0')}`;
  }
  next();
});

export default mongoose.model('Payment', paymentSchema);
